# Generated by Django 5.2.1 on 2025-06-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_time', models.IntegerField(blank=True, help_text='予定作業時間 (分)', null=True)),
                ('status', models.CharField(choices=[('pending', '未着手'), ('in_progress', '進行中'), ('completed', '完了'), ('snoozed', '延期')], default='pending', max_length=20)),
                ('is_daily_top', models.BooleanField(default=False, help_text='今日の表示タスク3つに含まれるか')),
                ('order_in_daily', models.IntegerField(blank=True, help_text='今日の表示タスク内の順序', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('snooze_reason', models.TextField(blank=True, null=True)),
                ('snooze_count', models.IntegerField(default=0)),
                ('learned_at_completion', models.TextField(blank=True, help_text='完了時に学んだこと', null=True)),
                ('category', models.CharField(blank=True, help_text='仕事, 学習, プライベートなど', max_length=50, null=True)),
                ('related_status_type', models.CharField(blank=True, choices=[('learning', '学習力'), ('creativity', '創造力'), ('execution', '実行力'), ('communication', 'コミュニケーション力')], help_text='上昇するステータス', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('learning', '学習力'), ('creativity', '創造力'), ('execution', '実行力'), ('communication', 'コミュニケーション力')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
